package orgs

import (
	"context"
	"errors"
	"fmt"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"

	"github.com/pyaas/saathi-backend/internal/domain"
	"github.com/pyaas/saathi-backend/internal/platform/httpx"
	"github.com/pyaas/saathi-backend/internal/platform/mongodb"
)

// repository is the module's only MongoDB access point. It reads the
// role_assignments and parties collections (allowed by spec for the members
// roster) but writes only org_units.
//
// Error contract: missing documents surface as httpx.NotFound (a business
// outcome); every other failure is returned as a raw error wrapped with the
// failing operation so the service can log it before mapping to a 500.
type repository struct {
	orgs        *mongo.Collection
	assignments *mongo.Collection
	parties     *mongo.Collection
	animals     *mongo.Collection // read-only: per-member ACTIVE animal counts for the roster
	pours       *mongo.Collection // read-only: per-member "poured today" flag for the roster
}

func newRepository(db *mongo.Database) *repository {
	return &repository{
		orgs:        db.Collection(mongodb.CollOrgUnits),
		assignments: db.Collection(mongodb.CollRoleAssignments),
		parties:     db.Collection(mongodb.CollParties),
		animals:     db.Collection(mongodb.CollAnimals),
		pours:       db.Collection(mongodb.CollMilkPours),
	}
}

// activeAnimalCountsByOwners returns, per owner party id, the count of ACTIVE
// animals owned — the roster's per-farmer animal count. Owners with no active
// animals are simply absent from the map (caller defaults to 0). A single
// grouped aggregation over the owner_party_id index.
func (r *repository) activeAnimalCountsByOwners(ctx context.Context, ownerIDs []primitive.ObjectID) (map[primitive.ObjectID]int, error) {
	out := map[primitive.ObjectID]int{}
	if len(ownerIDs) == 0 {
		return out, nil
	}
	cur, err := r.animals.Aggregate(ctx, mongo.Pipeline{
		{{Key: "$match", Value: bson.D{
			{Key: "owner_party_id", Value: bson.D{{Key: "$in", Value: ownerIDs}}},
			{Key: "status", Value: domain.AnimalStatusActive},
		}}},
		{{Key: "$group", Value: bson.D{
			{Key: "_id", Value: "$owner_party_id"},
			{Key: "n", Value: bson.D{{Key: "$sum", Value: 1}}},
		}}},
	})
	if err != nil {
		return nil, fmt.Errorf("count active animals by owner: %w", err)
	}
	var rows []struct {
		ID primitive.ObjectID `bson:"_id"`
		N  int                `bson:"n"`
	}
	if err := cur.All(ctx, &rows); err != nil {
		return nil, fmt.Errorf("decode active animal counts: %w", err)
	}
	for _, row := range rows {
		out[row.ID] = row.N
	}
	return out, nil
}

// pouredTodayByFarmers returns the set of farmer party ids that recorded a pour
// at dcsID on the given IST day key — the roster's "poured today" flag. A
// distinct read over the (dcs_id, pour_date) index.
func (r *repository) pouredTodayByFarmers(ctx context.Context, dcsID primitive.ObjectID, dayKey string, farmerIDs []primitive.ObjectID) (map[primitive.ObjectID]bool, error) {
	out := map[primitive.ObjectID]bool{}
	if len(farmerIDs) == 0 {
		return out, nil
	}
	raw, err := r.pours.Distinct(ctx, "farmer_party_id", bson.D{
		{Key: "dcs_id", Value: dcsID},
		{Key: "pour_date", Value: dayKey},
		{Key: "farmer_party_id", Value: bson.D{{Key: "$in", Value: farmerIDs}}},
	})
	if err != nil {
		return nil, fmt.Errorf("distinct poured-today farmers: %w", err)
	}
	for _, v := range raw {
		if id, ok := v.(primitive.ObjectID); ok {
			out[id] = true
		}
	}
	return out, nil
}

// insertOrg inserts a new org unit (its _id is pre-generated by the service).
// The driver error stays inspectable (%w) so the service can map a
// duplicate-key violation on code to a Conflict.
func (r *repository) insertOrg(ctx context.Context, org *domain.OrgUnit) error {
	if _, err := r.orgs.InsertOne(ctx, org); err != nil {
		return fmt.Errorf("insert org unit: %w", err)
	}
	return nil
}

// getOrg fetches one org unit by ObjectID.
func (r *repository) getOrg(ctx context.Context, id primitive.ObjectID) (*domain.OrgUnit, error) {
	var org domain.OrgUnit
	err := r.orgs.FindOne(ctx, bson.D{{Key: "_id", Value: id}}).Decode(&org)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return nil, httpx.NotFound("org unit " + id.Hex())
	}
	if err != nil {
		return nil, fmt.Errorf("get org unit %s: %w", id.Hex(), err)
	}
	return &org, nil
}

// countByType counts org units of the given type (federation-uniqueness check).
func (r *repository) countByType(ctx context.Context, orgType string) (int64, error) {
	n, err := r.orgs.CountDocuments(ctx, bson.D{{Key: "type", Value: orgType}})
	if err != nil {
		return 0, fmt.Errorf("count org units by type %s: %w", orgType, err)
	}
	return n, nil
}

// updateOrg applies a $set patch and returns the updated document.
func (r *repository) updateOrg(ctx context.Context, id primitive.ObjectID, set bson.D) (*domain.OrgUnit, error) {
	var org domain.OrgUnit
	err := r.orgs.FindOneAndUpdate(ctx,
		bson.D{{Key: "_id", Value: id}},
		bson.D{{Key: "$set", Value: set}},
		options.FindOneAndUpdate().SetReturnDocument(options.After),
	).Decode(&org)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return nil, httpx.NotFound("org unit " + id.Hex())
	}
	if err != nil {
		return nil, fmt.Errorf("update org unit %s: %w", id.Hex(), err)
	}
	return &org, nil
}

// listChildren pages the direct children of an org unit (parent_id index)
// and returns the total child count for pagination meta.
func (r *repository) listChildren(ctx context.Context, parentID primitive.ObjectID, page httpx.Page) ([]domain.OrgUnit, int64, error) {
	filter := bson.D{{Key: "parent_id", Value: parentID}}
	total, err := r.orgs.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, fmt.Errorf("count org children: %w", err)
	}
	units, err := r.findOrgs(ctx, filter,
		options.Find().
			SetSort(bson.D{{Key: "code", Value: 1}}).
			SetSkip(page.Offset).
			SetLimit(page.Limit))
	if err != nil {
		return nil, 0, err
	}
	return units, total, nil
}

// listOrgs pages org units matching an arbitrary filter (type/district/code)
// and returns the total matching count for pagination meta.
func (r *repository) listOrgs(ctx context.Context, filter bson.D, page httpx.Page) ([]domain.OrgUnit, int64, error) {
	total, err := r.orgs.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, fmt.Errorf("count org units: %w", err)
	}
	units, err := r.findOrgs(ctx, filter,
		options.Find().
			SetSort(bson.D{{Key: "code", Value: 1}}).
			SetSkip(page.Offset).
			SetLimit(page.Limit))
	if err != nil {
		return nil, 0, err
	}
	return units, total, nil
}

// listDescendants returns every org unit whose ancestor Path contains rootID
// (path index, ObjectID array containment), capped at limit nodes.
func (r *repository) listDescendants(ctx context.Context, rootID primitive.ObjectID, limit int64) ([]domain.OrgUnit, error) {
	return r.findOrgs(ctx, bson.D{{Key: "path", Value: rootID}},
		options.Find().
			SetSort(bson.D{{Key: "code", Value: 1}}).
			SetLimit(limit))
}

func (r *repository) findOrgs(ctx context.Context, filter bson.D, opts *options.FindOptions) ([]domain.OrgUnit, error) {
	cur, err := r.orgs.Find(ctx, filter, opts)
	if err != nil {
		return nil, fmt.Errorf("find org units: %w", err)
	}
	units := []domain.OrgUnit{}
	if err := cur.All(ctx, &units); err != nil {
		return nil, fmt.Errorf("decode org units: %w", err)
	}
	return units, nil
}

// countActiveAssignments counts the ACTIVE role assignments at one org unit —
// the members-listing total.
func (r *repository) countActiveAssignments(ctx context.Context, orgID primitive.ObjectID) (int64, error) {
	n, err := r.assignments.CountDocuments(ctx, bson.D{
		{Key: "org_unit_id", Value: orgID},
		{Key: "status", Value: domain.RoleAssignmentActive},
	})
	if err != nil {
		return 0, fmt.Errorf("count active role assignments: %w", err)
	}
	return n, nil
}

// listActiveAssignments pages the ACTIVE role assignments at one org unit
// (org_unit_id + role_code + status index).
func (r *repository) listActiveAssignments(ctx context.Context, orgID primitive.ObjectID, page httpx.Page) ([]domain.RoleAssignment, error) {
	cur, err := r.assignments.Find(ctx,
		bson.D{
			{Key: "org_unit_id", Value: orgID},
			{Key: "status", Value: domain.RoleAssignmentActive},
		},
		options.Find().
			SetSort(bson.D{{Key: "role_code", Value: 1}, {Key: "created_at", Value: 1}}).
			SetSkip(page.Offset).
			SetLimit(page.Limit))
	if err != nil {
		return nil, fmt.Errorf("find active role assignments: %w", err)
	}
	assignments := []domain.RoleAssignment{}
	if err := cur.All(ctx, &assignments); err != nil {
		return nil, fmt.Errorf("decode role assignments: %w", err)
	}
	return assignments, nil
}

// partiesByIDs fetches the given parties keyed by ObjectID for the in-memory join.
func (r *repository) partiesByIDs(ctx context.Context, ids []primitive.ObjectID) (map[primitive.ObjectID]domain.Party, error) {
	byID := make(map[primitive.ObjectID]domain.Party, len(ids))
	if len(ids) == 0 {
		return byID, nil
	}
	cur, err := r.parties.Find(ctx, bson.D{{Key: "_id", Value: bson.D{{Key: "$in", Value: ids}}}})
	if err != nil {
		return nil, fmt.Errorf("find parties: %w", err)
	}
	var parties []domain.Party
	if err := cur.All(ctx, &parties); err != nil {
		return nil, fmt.Errorf("decode parties: %w", err)
	}
	for _, p := range parties {
		byID[p.ID] = p
	}
	return byID, nil
}
