package quality

import (
	"context"
	"errors"
	"fmt"
	"time"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"

	"github.com/pyaas/saathi-backend/internal/domain"
	"github.com/pyaas/saathi-backend/internal/platform/httpx"
	"github.com/pyaas/saathi-backend/internal/platform/mongodb"
)

// repository is all MongoDB access for the quality module. It owns qc_results
// and — as the safety-gate verdict writer (blueprint §8.3) — performs the
// documented cross-collection status write onto bmc_lots and
// processing_batches. No other module may flip those gate statuses.
type repository struct {
	results      *mongo.Collection
	bmcLots      *mongo.Collection
	batches      *mongo.Collection
	counters     *mongo.Collection
	certificates *mongo.Collection
	consignments *mongo.Collection // per-samiti batches: F7 QC queue reads + the sanctioned QC verdict write
	// Per-samiti batch QC (F7): this module owns the consignment_qc results and
	// the auto-minted consignment batch QRs.
	consignmentQC *mongo.Collection
	batchQRs      *mongo.Collection
}

// newRepository binds the repository to its collections.
func newRepository(db *mongo.Database) *repository {
	return &repository{
		results:       db.Collection(mongodb.CollQCResults),
		bmcLots:       db.Collection(mongodb.CollBMCLots),
		batches:       db.Collection(mongodb.CollBatches),
		counters:      db.Collection(mongodb.CollCounters),
		certificates:  db.Collection(mongodb.CollQCCertificates),
		consignments:  db.Collection(mongodb.CollConsignments),
		consignmentQC: db.Collection(mongodb.CollConsignmentQC),
		batchQRs:      db.Collection(mongodb.CollConsignmentBatchQRs),
	}
}

// societyContribution is one DCS's share of a batch, aggregated from the
// consignments that fed it (via its BMC lots) — litres poured, pour count and
// the earliest collection date.
type societyContribution struct {
	Litres      float64
	PourCount   int
	CollectedOn string
}

// consignmentContributions resolves a batch's BMC lots to the consignments that
// fed them and aggregates, per contributing DCS, the litres, pour count and
// earliest collection date — the weighted per-society breakdown the trace-back
// screen renders (§7.4 honest set-valued pooling). Read-only across bmc_lots and
// dcs_consignments (sanctioned by the trace-back use case).
func (r *repository) consignmentContributions(ctx context.Context, bmcLotIDs []primitive.ObjectID) (map[primitive.ObjectID]societyContribution, error) {
	out := map[primitive.ObjectID]societyContribution{}
	if len(bmcLotIDs) == 0 {
		return out, nil
	}
	// 1) BMC lots → the union of their consignment ids.
	lotCur, err := r.bmcLots.Find(ctx,
		bson.D{{Key: "_id", Value: bson.D{{Key: "$in", Value: bmcLotIDs}}}},
		options.Find().SetProjection(bson.D{{Key: "consignment_ids", Value: 1}}))
	if err != nil {
		return nil, httpx.Internal(fmt.Errorf("trace-back: load bmc lots: %w", err))
	}
	var lotRows []struct {
		ConsignmentIDs []primitive.ObjectID `bson:"consignment_ids"`
	}
	if err := lotCur.All(ctx, &lotRows); err != nil {
		return nil, httpx.Internal(fmt.Errorf("trace-back: decode bmc lots: %w", err))
	}
	seen := map[primitive.ObjectID]struct{}{}
	consIDs := make([]primitive.ObjectID, 0)
	for _, lr := range lotRows {
		for _, id := range lr.ConsignmentIDs {
			if _, ok := seen[id]; ok {
				continue
			}
			seen[id] = struct{}{}
			consIDs = append(consIDs, id)
		}
	}
	if len(consIDs) == 0 {
		return out, nil
	}
	// 2) Consignments → per-DCS litres/pour-count/date.
	consCur, err := r.consignments.Find(ctx,
		bson.D{{Key: "_id", Value: bson.D{{Key: "$in", Value: consIDs}}}},
		options.Find().SetProjection(bson.D{
			{Key: "dcs_id", Value: 1}, {Key: "total_quantity_litres", Value: 1},
			{Key: "pour_ids", Value: 1}, {Key: "date", Value: 1},
		}))
	if err != nil {
		return nil, httpx.Internal(fmt.Errorf("trace-back: load consignments: %w", err))
	}
	var consRows []struct {
		DCSID   primitive.ObjectID   `bson:"dcs_id"`
		Litres  float64              `bson:"total_quantity_litres"`
		PourIDs []primitive.ObjectID `bson:"pour_ids"`
		Date    string               `bson:"date"`
	}
	if err := consCur.All(ctx, &consRows); err != nil {
		return nil, httpx.Internal(fmt.Errorf("trace-back: decode consignments: %w", err))
	}
	for _, cr := range consRows {
		c := out[cr.DCSID]
		c.Litres += cr.Litres
		c.PourCount += len(cr.PourIDs)
		if c.CollectedOn == "" || (cr.Date != "" && cr.Date < c.CollectedOn) {
			c.CollectedOn = cr.Date
		}
		out[cr.DCSID] = c
	}
	return out, nil
}

// insertResult stores a new QC result document (its _id is pre-generated by
// the service so provenance refs and the gate write share one ID).
func (r *repository) insertResult(ctx context.Context, res *domain.QCResult) error {
	if _, err := r.results.InsertOne(ctx, res); err != nil {
		return httpx.Internal(fmt.Errorf("insert qc result: %w", err))
	}
	return nil
}

// setResultProvenanceSeq stamps the ledger sequence onto a stored result.
func (r *repository) setResultProvenanceSeq(ctx context.Context, resultID primitive.ObjectID, seq int64) error {
	_, err := r.results.UpdateOne(ctx,
		bson.D{{Key: "_id", Value: resultID}},
		bson.D{{Key: "$set", Value: bson.D{{Key: "provenance_seq", Value: seq}}}},
	)
	if err != nil {
		return httpx.Internal(fmt.Errorf("set qc result provenance seq: %w", err))
	}
	return nil
}

// markResultSuperseded voids a result that lost the gate race — the subject's
// verdict came from a different, earlier result.
func (r *repository) markResultSuperseded(ctx context.Context, resultID primitive.ObjectID) error {
	_, err := r.results.UpdateOne(ctx,
		bson.D{{Key: "_id", Value: resultID}},
		bson.D{{Key: "$set", Value: bson.D{{Key: "superseded", Value: true}}}},
	)
	if err != nil {
		return httpx.Internal(fmt.Errorf("mark qc result superseded: %w", err))
	}
	return nil
}

// findResultByID returns one QC result or NotFound.
func (r *repository) findResultByID(ctx context.Context, resultID primitive.ObjectID) (*domain.QCResult, error) {
	var res domain.QCResult
	err := r.results.FindOne(ctx, bson.D{{Key: "_id", Value: resultID}}).Decode(&res)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return nil, httpx.NotFound("qc result")
	}
	if err != nil {
		return nil, httpx.Internal(fmt.Errorf("find qc result: %w", err))
	}
	return &res, nil
}

// listResults returns a page of QC results, newest first, optionally filtered
// by subject (a zero subjectID means "no subject filter"). It also returns
// the total matching count for pagination meta.
func (r *repository) listResults(ctx context.Context, subjectType string, subjectID primitive.ObjectID, page httpx.Page) ([]domain.QCResult, int64, error) {
	filter := bson.D{}
	if subjectType != "" {
		filter = append(filter, bson.E{Key: "subject_type", Value: subjectType})
	}
	if !subjectID.IsZero() {
		filter = append(filter, bson.E{Key: "subject_id", Value: subjectID})
	}

	total, err := r.results.CountDocuments(ctx, filter)
	if err != nil {
		return nil, 0, httpx.Internal(fmt.Errorf("count qc results: %w", err))
	}

	cur, err := r.results.Find(ctx, filter, options.Find().
		SetSort(bson.D{{Key: "recorded_at", Value: -1}}).
		SetSkip(page.Offset).
		SetLimit(page.Limit),
	)
	if err != nil {
		return nil, 0, httpx.Internal(fmt.Errorf("list qc results: %w", err))
	}
	results := []domain.QCResult{}
	if err := cur.All(ctx, &results); err != nil {
		return nil, 0, httpx.Internal(fmt.Errorf("decode qc results: %w", err))
	}
	return results, total, nil
}

// findBMCLot returns a BMC lot or NotFound.
func (r *repository) findBMCLot(ctx context.Context, lotID primitive.ObjectID) (*domain.BMCLot, error) {
	var lot domain.BMCLot
	err := r.bmcLots.FindOne(ctx, bson.D{{Key: "_id", Value: lotID}}).Decode(&lot)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return nil, httpx.NotFound("bmc lot")
	}
	if err != nil {
		return nil, httpx.Internal(fmt.Errorf("find bmc lot: %w", err))
	}
	return &lot, nil
}

// findBatch returns a processing batch or NotFound.
func (r *repository) findBatch(ctx context.Context, batchID primitive.ObjectID) (*domain.ProcessingBatch, error) {
	var batch domain.ProcessingBatch
	err := r.batches.FindOne(ctx, bson.D{{Key: "_id", Value: batchID}}).Decode(&batch)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return nil, httpx.NotFound("processing batch")
	}
	if err != nil {
		return nil, httpx.Internal(fmt.Errorf("find processing batch: %w", err))
	}
	return &batch, nil
}

// gateBMCLot applies the gate verdict to a BMC lot still in QC_PENDING.
// Returns false when the lot was already gated by a concurrent writer.
func (r *repository) gateBMCLot(ctx context.Context, lotID, resultID primitive.ObjectID, newStatus, blockReason string) (bool, error) {
	return gateSubjectDoc(ctx, r.bmcLots, lotID, domain.BMCLotStatusQCPending, resultID, newStatus, blockReason)
}

// gateBatch applies the gate verdict to a processing batch still in QC_PENDING.
// Returns false when the batch was already gated by a concurrent writer.
func (r *repository) gateBatch(ctx context.Context, batchID, resultID primitive.ObjectID, newStatus, blockReason string) (bool, error) {
	return gateSubjectDoc(ctx, r.batches, batchID, domain.BatchStatusQCPending, resultID, newStatus, blockReason)
}

// gateSubjectDoc is the shared conditional gate write: the filter pins the
// subject to QC_PENDING so a lost race cannot double-apply a verdict — the
// optimistic pattern that replaces transactions on a standalone server.
func gateSubjectDoc(ctx context.Context, coll *mongo.Collection, subjectID primitive.ObjectID, pendingStatus string, resultID primitive.ObjectID, newStatus, blockReason string) (bool, error) {
	set := bson.D{{Key: "status", Value: newStatus}}
	if blockReason != "" {
		set = append(set, bson.E{Key: "block_reason", Value: blockReason})
	}
	res, err := coll.UpdateOne(ctx,
		bson.D{{Key: "_id", Value: subjectID}, {Key: "status", Value: pendingStatus}},
		bson.D{
			{Key: "$set", Value: set},
			{Key: "$push", Value: bson.D{{Key: "qc_result_ids", Value: resultID}}},
		},
	)
	if err != nil {
		return false, httpx.Internal(fmt.Errorf("gate %s subject %s: %w", coll.Name(), subjectID.Hex(), err))
	}
	return res.MatchedCount == 1, nil
}

// resolveSubjectGate flips a QUARANTINED subject to PASSED (verdict PASS) or
// BLOCKED (verdict REJECT) — the HOLD-resolution counterpart of gateSubjectDoc.
// The QUARANTINED filter is the concurrency guard; the qc_result_ids roster is
// NOT re-pushed (the hold gate already listed the result). Returns false when
// the subject was resolved concurrently.
func (r *repository) resolveSubjectGate(ctx context.Context, subjectType string, subjectID primitive.ObjectID, verdict, blockReason string) (bool, error) {
	var coll *mongo.Collection
	var quarantined, passed, blocked string
	switch subjectType {
	case domain.QCSubjectBMCLot:
		coll = r.bmcLots
		quarantined, passed, blocked = domain.BMCLotStatusQuarantined, domain.BMCLotStatusPassed, domain.BMCLotStatusBlocked
	case domain.QCSubjectProcessingBatch:
		coll = r.batches
		quarantined, passed, blocked = domain.BatchStatusQuarantined, domain.BatchStatusPassed, domain.BatchStatusBlocked
	default:
		return false, httpx.BadRequest("INVALID_SUBJECT_TYPE", "subject_type is not gate-eligible")
	}
	newStatus := blocked
	set := bson.D{{Key: "status", Value: newStatus}}
	if verdict == domain.QCVerdictPass {
		newStatus = passed
		set = bson.D{{Key: "status", Value: newStatus}, {Key: "block_reason", Value: ""}}
	} else if blockReason != "" {
		set = append(set, bson.E{Key: "block_reason", Value: blockReason})
	}
	res, err := coll.UpdateOne(ctx,
		bson.D{{Key: "_id", Value: subjectID}, {Key: "status", Value: quarantined}},
		bson.D{{Key: "$set", Value: set}},
	)
	if err != nil {
		return false, httpx.Internal(fmt.Errorf("resolve %s gate %s: %w", coll.Name(), subjectID.Hex(), err))
	}
	return res.MatchedCount == 1, nil
}

// resolveResult stamps the HOLD resolution onto the QC result document and
// returns the updated document.
func (r *repository) resolveResult(ctx context.Context, resultID primitive.ObjectID, verdict, certificate, blockReason, notes string, resolvedBy primitive.ObjectID, at time.Time) (*domain.QCResult, error) {
	set := bson.D{
		{Key: "verdict", Value: verdict},
		{Key: "overall_pass", Value: verdict == domain.QCVerdictPass},
		{Key: "resolved_by", Value: resolvedBy},
		{Key: "resolved_at", Value: at},
		{Key: "resolution_notes", Value: notes},
	}
	if certificate != "" {
		set = append(set, bson.E{Key: "certificate_number", Value: certificate})
	}
	if verdict == domain.QCVerdictReject && blockReason != "" {
		set = append(set, bson.E{Key: "failure_reasons", Value: []string{blockReason}})
	}
	var updated domain.QCResult
	err := r.results.FindOneAndUpdate(ctx,
		bson.D{{Key: "_id", Value: resultID}},
		bson.D{{Key: "$set", Value: set}},
		options.FindOneAndUpdate().SetReturnDocument(options.After),
	).Decode(&updated)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return nil, httpx.NotFound("qc result")
	}
	if err != nil {
		return nil, httpx.Internal(fmt.Errorf("resolve qc result %s: %w", resultID.Hex(), err))
	}
	return &updated, nil
}

// listBMCLotsByStatus returns every BMC lot in the given status, newest first.
func (r *repository) listBMCLotsByStatus(ctx context.Context, status string) ([]domain.BMCLot, error) {
	cur, err := r.bmcLots.Find(ctx,
		bson.D{{Key: "status", Value: status}},
		options.Find().SetSort(bson.D{{Key: "created_at", Value: 1}}),
	)
	if err != nil {
		return nil, httpx.Internal(fmt.Errorf("list bmc lots by status %s: %w", status, err))
	}
	lots := []domain.BMCLot{}
	if err := cur.All(ctx, &lots); err != nil {
		return nil, httpx.Internal(fmt.Errorf("decode bmc lots: %w", err))
	}
	return lots, nil
}

// listBatchesByStatus returns every processing batch in the given status,
// oldest first (a QC queue is worked front-to-back).
func (r *repository) listBatchesByStatus(ctx context.Context, status string) ([]domain.ProcessingBatch, error) {
	cur, err := r.batches.Find(ctx,
		bson.D{{Key: "status", Value: status}},
		options.Find().SetSort(bson.D{{Key: "created_at", Value: 1}}),
	)
	if err != nil {
		return nil, httpx.Internal(fmt.Errorf("list batches by status %s: %w", status, err))
	}
	batches := []domain.ProcessingBatch{}
	if err := cur.All(ctx, &batches); err != nil {
		return nil, httpx.Internal(fmt.Errorf("decode batches: %w", err))
	}
	return batches, nil
}

// recordedTestNames returns the set of canonical test names already recorded
// for a subject across its non-superseded QC results. For a QC_PENDING subject
// this is typically empty, but it stays correct if a partial/superseded result
// exists — the queue then honestly reports which parameters are on file.
func (r *repository) recordedTestNames(ctx context.Context, subjectType string, subjectID primitive.ObjectID) (map[string]bool, error) {
	cur, err := r.results.Find(ctx, bson.D{
		{Key: "subject_type", Value: subjectType},
		{Key: "subject_id", Value: subjectID},
		{Key: "superseded", Value: bson.D{{Key: "$ne", Value: true}}},
	})
	if err != nil {
		return nil, httpx.Internal(fmt.Errorf("find qc results for subject %s: %w", subjectID.Hex(), err))
	}
	var results []domain.QCResult
	if err := cur.All(ctx, &results); err != nil {
		return nil, httpx.Internal(fmt.Errorf("decode qc results for subject: %w", err))
	}
	names := map[string]bool{}
	for _, res := range results {
		for _, t := range res.Tests {
			names[t.Name] = true
		}
	}
	return names, nil
}

// findCertificateByBatch returns the certificate already issued for a batch, or
// mongo.ErrNoDocuments when none exists — the idempotency guard behind a single
// certificate per batch.
func (r *repository) findCertificateByBatch(ctx context.Context, batchID primitive.ObjectID) (*domain.QCCertificate, error) {
	var cert domain.QCCertificate
	if err := r.certificates.FindOne(ctx, bson.D{{Key: "batch_id", Value: batchID}}).Decode(&cert); err != nil {
		return nil, err
	}
	return &cert, nil
}

// insertCertificate persists a new QC certificate document. The per-batch
// idempotency guard runs in the service before this insert; a certificate_number
// collision (unique index) still surfaces as a 409 so a retry storm cannot mint
// colliding certificates.
func (r *repository) insertCertificate(ctx context.Context, cert *domain.QCCertificate) error {
	if _, err := r.certificates.InsertOne(ctx, cert); err != nil {
		if mongo.IsDuplicateKeyError(err) {
			return httpx.Conflict("ALREADY_ISSUED", "a certificate has already been issued for this batch")
		}
		return httpx.Internal(fmt.Errorf("insert qc certificate: %w", err))
	}
	return nil
}

// nextCertificateSeq atomically increments and returns the per-stage QC
// certificate counter (counters collection, upsert-on-first-use). Counter
// keys are human-readable strings by design — they are not entity references.
func (r *repository) nextCertificateSeq(ctx context.Context, stage string) (int64, error) {
	var doc struct {
		Seq int64 `bson:"seq"`
	}
	err := r.counters.FindOneAndUpdate(ctx,
		bson.D{{Key: "_id", Value: "qc_certificate:" + stage}},
		bson.D{{Key: "$inc", Value: bson.D{{Key: "seq", Value: int64(1)}}}},
		options.FindOneAndUpdate().SetUpsert(true).SetReturnDocument(options.After),
	).Decode(&doc)
	if err != nil {
		return 0, httpx.Internal(fmt.Errorf("next qc certificate seq: %w", err))
	}
	return doc.Seq, nil
}
